# Generated by Django 5.1.3 on 2025-03-26 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_seller_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
